### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mareksagan** [mohamedosama113/k8s-helm-terraform#1]
Hey, do you have this issue?

**Comment by mohamedosama113** [comment]
Yes i have why ?

**Comment by mareksagan** [comment]
It's just easier to communicate there. If you don't mind, I would like to add you. Is that okay with you?

**Comment by mohamedosama113** [comment]
I'm very sorry i just communicate on upwork for the work

**Comment by mareksagan** [comment]
Ok

**Comment by mohamedosama113** [comment]
If you have any issue feel free to ask i will always be here for helping you. Good night marek
